name: Windows Build

on:
  workflow_call:
    inputs:
      build_number:
        required: true
        type: string
      prebuilds_only:
        required: true
        type: string
    secrets:
      APPLE_API_KEY:
        required: false
      APPLE_API_KEY_ID:
        required: false
      APPLE_API_ISSUER:
        required: false
      APPLE_TEAM_PREFIX:
        required: false

jobs:
  build:
    env:
      UPDATE_FEED_OWNER: deepnest-next
      UPDATE_FEED_REPOSITORY: deepnest
      BUILD_NUMBER: ${{ inputs.build_number }}
      PREBUILDS_ONLY: ${{ inputs.prebuilds_only }}
    
    strategy:
      matrix:
        os: ["windows-latest"]
        arch: ["x64", "arm64"]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Install distribution dependencies
        shell: bash
        run: |
          dotnet tool install -g vpk;
          # Uncomment if needed
          # choco install -y nsis;
          # choco install wixtoolset  --version=3.14.0;

      - name: Setup Node (v22)
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22"
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        shell: bash
        run: |
          npm install -g npm@latest
          npm ci

      - name: Build (${{ matrix.arch }})
        uses: DeineAgenturUG/retry@6278ba3ea01ddc52e75d82766fca6cf4d35835cd
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            mkdir -p out/make/
            npm run make -- --arch ${{ matrix.arch }}
            find ./out -type f
          shell: bash
        env:
          CI: "true"
          BUILD_NUMBER: ${{ inputs.build_number }}
          MAKER_ARCH: ${{ matrix.arch }}

      - name: Upload artifacts (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.arch }}
          retention-days: 1
          path: |
            out/make/